package com.hhjs.psi.inventory.entity;

public enum StockRecordSubType {
    PRODUCTION,
    PURCHASE,
    SALES,
    PRODUCTION_USAGE,
    INTERNAL_USAGE,
    OTHER_OUTBOUND,
    PRODUCTION_LOSS,
    PACKAGING_LOSS,
    SHIPPING_LOSS,
    EXPIRED_LOSS,
    DAMAGE_LOSS,
    OTHER_LOSS,
    INVENTORY,
    INVENTORY_GAIN,
    INVENTORY_LOSS
}
